local open Const in
val predef_variables = [
  {qual="General", id="global_data"},
  {qual="General", id="s_irusr"},
  {qual="General", id="s_iwusr"},
  {qual="General", id="s_ixusr"},
  {qual="General", id="s_irgrp"},
  {qual="General", id="s_iwgrp"},
  {qual="General", id="s_ixgrp"},
  {qual="General", id="s_iroth"},
  {qual="General", id="s_iwoth"},
  {qual="General", id="s_ixoth"},
  {qual="General", id="s_isuid"},
  {qual="General", id="s_isgid"},
  {qual="General", id="s_irall"},
  {qual="General", id="s_iwall"},
  {qual="General", id="s_ixall"},
  {qual="General", id="command_line"},
  {qual="General", id="interactive"},
  {qual="General", id="max_string_length"},
  {qual="General", id="max_vect_length"},
  {qual="General", id="exn_memory"},
  {qual="General", id="exn_argument"},
  {qual="General", id="exn_graphic"},
  {qual="General", id="exn_syserr"},
  {qual="General", id="exn_fail"},
  {qual="General", id="exn_size"},
  {qual="General", id="exn_interrupt"},
  {qual="General", id="exn_subscript"},
  {qual="General", id="exn_chr"},
  {qual="General", id="exn_div"},
  {qual="General", id="exn_domain"},
  {qual="General", id="exn_ord"},
  {qual="General", id="exn_overflow"},
  {qual="General", id="exn_bind"},
  {qual="General", id="exn_match"},
  {qual="General", id="exn_io"},
  {qual="General", id="exn_option"},
  {qual="General", id="exn_span"},
  {qual="General", id="val_exn_interrupt"},
  {qual="General", id="val_exn_div"},
  {qual="General", id="val_exn_overflow"}
];
end;
