#!/bin/bash
cc=$HOME/project/mosml2.10-new/bin/mosmlc
mosmllib=$HOME/Repos/mosml-js/src/jslibs/mosmllib.js

smlfile=""
jsfile=""
tmpfile=""
uselibjs=false
uselibsml=true
showlambda=true
translatefirst=true
beautify=true
closure=false

while : ; do
    case $1 in
    "")
        break
        ;;
    *.sml)
        translatefirst=true
        smlfile=$1
        jsfile=${1/sml/js}
        tmpfile=${1/sml/tmp.js}
        ;;
    *.js)
        translatefirst=false
        jsfile=$1
        tmpfile=${1/js/tmp.js}
        ;;
    -lib)
        uselibjs=true
        uselibsml=true
        ;;
    -no-lib)
        uselibsml=false
        uselibjs=false
        ;;
    -no-lambda)
        showlambda=false
        ;;
    -no-jsbeautify)
        beautify=false
        ;;
    -*)
        echo "Unknown option \"$1\", ignored" >&2
        ;;
    *)
        echo "I don't know what to do with file \"$1\", ignored" >&2
        ;;
  esac
  shift
done

if $translatefirst; then
    if $showlambda; then
        echo "==============================LAMBDA BEGIN=============================="
        $cc -c $smlfile
        echo "==============================LAMBDA END================================"
    else
        $cc -c $smlfile > /dev/null
    fi
    if $uselibsml; then
        cat $mosmllib > $tmpfile
        cat $jsfile >> $tmpfile
    else
        cat $jsfile > $tmpfile
    fi
    if $beautify; then
        js-beautify -r $jsfile
    fi
else
    if $uselibjs; then
        cat $mosmllib > $tmpfile
        cat $jsfile >> $tmpfile
    else
        cat $jsfile > $tmpfile
    fi
fi
echo "==============================JS BEGIN=============================="
node $tmpfile
echo "==============================JS END================================"
rm $tmpfile

exit 0